package org.xuefeng.mssms.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseid
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.coursename
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String coursename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseid
     *
     * @return the value of course.courseid
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseid
     *
     * @param courseid the value for course.courseid
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid == null ? null : courseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.coursename
     *
     * @return the value of course.coursename
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.coursename
     *
     * @param coursename the value for course.coursename
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }
}