package org.xuefeng.mssms.entity;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.stuno
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String stuno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.courseid
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private Float score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.stuno
     *
     * @return the value of score.stuno
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getStuno() {
        return stuno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.stuno
     *
     * @param stuno the value for score.stuno
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setStuno(String stuno) {
        this.stuno = stuno == null ? null : stuno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.courseid
     *
     * @return the value of score.courseid
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.courseid
     *
     * @param courseid the value for score.courseid
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid == null ? null : courseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setScore(Float score) {
        this.score = score;
    }
}