package org.xuefeng.mssms.entity;

import java.util.ArrayList;
import java.util.List;

public class TeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public TeacherExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTeachnoIsNull() {
            addCriterion("teachno is null");
            return (Criteria) this;
        }

        public Criteria andTeachnoIsNotNull() {
            addCriterion("teachno is not null");
            return (Criteria) this;
        }

        public Criteria andTeachnoEqualTo(String value) {
            addCriterion("teachno =", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoNotEqualTo(String value) {
            addCriterion("teachno <>", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoGreaterThan(String value) {
            addCriterion("teachno >", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoGreaterThanOrEqualTo(String value) {
            addCriterion("teachno >=", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoLessThan(String value) {
            addCriterion("teachno <", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoLessThanOrEqualTo(String value) {
            addCriterion("teachno <=", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoLike(String value) {
            addCriterion("teachno like", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoNotLike(String value) {
            addCriterion("teachno not like", value, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoIn(List<String> values) {
            addCriterion("teachno in", values, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoNotIn(List<String> values) {
            addCriterion("teachno not in", values, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoBetween(String value1, String value2) {
            addCriterion("teachno between", value1, value2, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnoNotBetween(String value1, String value2) {
            addCriterion("teachno not between", value1, value2, "teachno");
            return (Criteria) this;
        }

        public Criteria andTeachnameIsNull() {
            addCriterion("teachname is null");
            return (Criteria) this;
        }

        public Criteria andTeachnameIsNotNull() {
            addCriterion("teachname is not null");
            return (Criteria) this;
        }

        public Criteria andTeachnameEqualTo(String value) {
            addCriterion("teachname =", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameNotEqualTo(String value) {
            addCriterion("teachname <>", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameGreaterThan(String value) {
            addCriterion("teachname >", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameGreaterThanOrEqualTo(String value) {
            addCriterion("teachname >=", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameLessThan(String value) {
            addCriterion("teachname <", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameLessThanOrEqualTo(String value) {
            addCriterion("teachname <=", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameLike(String value) {
            addCriterion("teachname like", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameNotLike(String value) {
            addCriterion("teachname not like", value, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameIn(List<String> values) {
            addCriterion("teachname in", values, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameNotIn(List<String> values) {
            addCriterion("teachname not in", values, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameBetween(String value1, String value2) {
            addCriterion("teachname between", value1, value2, "teachname");
            return (Criteria) this;
        }

        public Criteria andTeachnameNotBetween(String value1, String value2) {
            addCriterion("teachname not between", value1, value2, "teachname");
            return (Criteria) this;
        }

        public Criteria andCourseIsNull() {
            addCriterion("course is null");
            return (Criteria) this;
        }

        public Criteria andCourseIsNotNull() {
            addCriterion("course is not null");
            return (Criteria) this;
        }

        public Criteria andCourseEqualTo(String value) {
            addCriterion("course =", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseNotEqualTo(String value) {
            addCriterion("course <>", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseGreaterThan(String value) {
            addCriterion("course >", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseGreaterThanOrEqualTo(String value) {
            addCriterion("course >=", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseLessThan(String value) {
            addCriterion("course <", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseLessThanOrEqualTo(String value) {
            addCriterion("course <=", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseLike(String value) {
            addCriterion("course like", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseNotLike(String value) {
            addCriterion("course not like", value, "course");
            return (Criteria) this;
        }

        public Criteria andCourseIn(List<String> values) {
            addCriterion("course in", values, "course");
            return (Criteria) this;
        }

        public Criteria andCourseNotIn(List<String> values) {
            addCriterion("course not in", values, "course");
            return (Criteria) this;
        }

        public Criteria andCourseBetween(String value1, String value2) {
            addCriterion("course between", value1, value2, "course");
            return (Criteria) this;
        }

        public Criteria andCourseNotBetween(String value1, String value2) {
            addCriterion("course not between", value1, value2, "course");
            return (Criteria) this;
        }

        public Criteria andPsdIsNull() {
            addCriterion("psd is null");
            return (Criteria) this;
        }

        public Criteria andPsdIsNotNull() {
            addCriterion("psd is not null");
            return (Criteria) this;
        }

        public Criteria andPsdEqualTo(String value) {
            addCriterion("psd =", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdNotEqualTo(String value) {
            addCriterion("psd <>", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdGreaterThan(String value) {
            addCriterion("psd >", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdGreaterThanOrEqualTo(String value) {
            addCriterion("psd >=", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdLessThan(String value) {
            addCriterion("psd <", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdLessThanOrEqualTo(String value) {
            addCriterion("psd <=", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdLike(String value) {
            addCriterion("psd like", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdNotLike(String value) {
            addCriterion("psd not like", value, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdIn(List<String> values) {
            addCriterion("psd in", values, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdNotIn(List<String> values) {
            addCriterion("psd not in", values, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdBetween(String value1, String value2) {
            addCriterion("psd between", value1, value2, "psd");
            return (Criteria) this;
        }

        public Criteria andPsdNotBetween(String value1, String value2) {
            addCriterion("psd not between", value1, value2, "psd");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 21 13:47:44 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}