package org.xuefeng.mssms.entity;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teachno
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String teachno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teachname
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String teachname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.course
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.psd
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String psd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.sex
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.id
     *
     * @return the value of teacher_info.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.id
     *
     * @param id the value for teacher_info.id
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teachno
     *
     * @return the value of teacher_info.teachno
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getTeachno() {
        return teachno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teachno
     *
     * @param teachno the value for teacher_info.teachno
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setTeachno(String teachno) {
        this.teachno = teachno == null ? null : teachno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teachname
     *
     * @return the value of teacher_info.teachname
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getTeachname() {
        return teachname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teachname
     *
     * @param teachname the value for teacher_info.teachname
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setTeachname(String teachname) {
        this.teachname = teachname == null ? null : teachname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.course
     *
     * @return the value of teacher_info.course
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.course
     *
     * @param course the value for teacher_info.course
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.psd
     *
     * @return the value of teacher_info.psd
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getPsd() {
        return psd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.psd
     *
     * @param psd the value for teacher_info.psd
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setPsd(String psd) {
        this.psd = psd == null ? null : psd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.sex
     *
     * @return the value of teacher_info.sex
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.sex
     *
     * @param sex the value for teacher_info.sex
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}