package org.xuefeng.mssms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xuefeng.mssms.entity.Score;
import org.xuefeng.mssms.entity.ScoreExample;

public interface ScoreMapper {

    List<Score> selectScoreByStuno(String stuno);

    List<Score> selectScoreByCourseid(String courseid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    long countByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int deleteByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    List<Score> selectByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    Score selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByExample(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByPrimaryKey(Score record);
}