package org.xuefeng.mssms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xuefeng.mssms.entity.Teacher;
import org.xuefeng.mssms.entity.TeacherExample;

public interface TeacherMapper {

    Teacher selectTeacherByTeachno(String teachno);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    long countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Sat Mar 21 13:47:44 CST 2020
     */
    int updateByPrimaryKey(Teacher record);

    int updatePasswordByTeachNo(Teacher teacher);
}